# null -> default

# Data
data:
  root: dataset/MMAD
  # root: /content/dataset/MMAD
  output_root: ./output

# Anomaly Detection Model
anomaly:
  model: efficientad  # patchcore | winclip | efficientad

  patchcore:
    backbone: null
    layers: null
    coreset_sampling_ratio: null

  winclip:
    class_name: null
    k_shot: null
    scales: null

  efficientad:
    model_size: null
    teacher_out_channels: null
    visualizer: false
    evaluator: true
    imagenet_dir: imagenette/train

# Training
training:
  train_batch_size: 1
  eval_batch_size: 1
  num_workers: null
  max_epochs: 100  # null -> model default

# Engine
engine:
  accelerator: auto  # auto | cpu | gpu | mps # Mac은 cpu 권장 mps 호환성 문제 심함
  enable_progress_bar: false
  logger: wandb


# Output
output:
  save_json: true